spring.application.name=sistema

# Conexão direta no localhost usando a sua Autenticação do Windows
spring.datasource.url=jdbc:sqlserver://WIN-5QPMJCK74FT:1433;databaseName=HardSoftDB;encrypt=false;trustServerCertificate=true;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# O Spring vai criar e atualizar as tabelas sozinho
spring.jpa.hibernate.ddl-auto=create

# spring.jpa.hibernate.ddl-auto=create

spring.datasource.username=sa
spring.datasource.password=sa
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true

# Mostra no console os comandos SQL que ele gera
spring.jpa.show-sql=true